'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('zh-CN');
const today=()=>new Date().toLocaleDateString('sv-SE');
const defaults=()=>({campaign:{title:'把夜晚，还给自己',coupon:10,end:'2026-10-31',active:true},claimed:null,checkins:[],orders:[],contents:[{id:1,title:'今天，就到这里。',channel:'抖音',status:'演示已发布',body:'15 秒下班切换：合上电脑，整理桌面，展示产品与活动主题。镜头中的产品使用方式需先核对标签。'},{id:2,title:'我的下班仪式，终于不用再打卡效率了',channel:'小红书',status:'待审核',body:'六页图文：下班桌面、阅读时间、产品规格、新手问答与晚间习惯。合作内容需标注。'},{id:3,title:'买第一瓶精油前，先看这 3 件事',channel:'官网',status:'草稿',body:'确认产品类型与标签，阅读适用方式和注意事项，核对店铺主体与售后。'},{id:4,title:'欢迎来到晚间留白',channel:'微信',status:'草稿',body:'今晚不用完成很多事，给自己留十分钟就好。先读使用说明，再选择适合自己的晚间习惯。'}]});
let state;try{state=JSON.parse(localStorage.getItem('evening-pages-demo-v1'))||defaults();if(!state.campaign||!Array.isArray(state.contents))state=defaults()}catch{state=defaults()}
const BASE=document.body.dataset.base;
let renderedMiniPage=null;
let route=document.body.dataset.route,miniPage='home',adminPage='overview',period='7',contentFilter='全部渠道',contentQuery='',selectedScene='',toastTimer;
const save=()=>{try{localStorage.setItem('evening-pages-demo-v1',JSON.stringify(state))}catch{toast('浏览器无法保存，本次更改仅在当前页面有效')}};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3300)}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}
function closeModal(){$('#modal').close()}
$('#modal .close').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
const activeCampaign=()=>state.campaign.active&&state.campaign.end>=today();
const validCoupon=()=>state.claimed&&!state.claimed.used&&activeCampaign()&&state.claimed.end>=today()&&state.claimed.amount>0&&state.claimed.amount<99;
const payable=()=>99-(validCoupon()?state.claimed.amount:0);
function download(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function goto(r){location.href=BASE+(r==='admin'?'/admin/':'/mini/');}
const scenes={read:['阅读时刻','把手机放远一些，翻开一直想读的那一页。','选一本书','留十分钟阅读','记下一句喜欢的话'],work:['下班留白','今天的待办到这里，让桌面和心情都留一点空白。','合上工作电脑','整理一角桌面','写下今天的小收获'],weekend:['周末慢时光','今天不用赶路，给喜欢的小事多留一点时间。','选一段音乐','安静坐一会儿','记录一个舒服的瞬间']};
function mini(){return `<div class="mini-stage"><div class="mini-intro"><div class="eyebrow">EVENING, YOURS. / H5</div><h1>让一段晚间留白，<br>成为自己的日常。</h1><p>选一个今晚喜欢的场景，发现属于自己的小仪式。</p><div class="flow-list"><div><span class="circle">1</span><div>选择今晚的节奏<p>阅读、下班、周末，找到你的场景。</p></div></div><div><span class="circle">2</span><div>获得一份仪式建议<p>领取模拟权益，了解产品与规则。</p></div></div><div><span class="circle">3</span><div>在七天里，留住小习惯<p>记录一件今晚的小事，给自己留一点空白。</p></div></div></div><div class="source-note">浏览器版小程序体验。权益和下单仅供模拟，不收款或发货。</div></div><div class="phone"><div class="phone-status"><span>9:41</span><span>•••　▰</span></div><div class="phone-top"><span>晚间留白</span><span class="wx-controls">••• │ ◎</span></div><div class="phone-body" id="phone-body">${miniBody()}</div><div class="phone-nav">${[['home','⌂','首页'],['ritual','◷','晚间仪式'],['mine','♧','我的']].map(([r,i,l])=>`<button data-action="mini-nav" data-value="${r}" class="${miniPage===r?'active':''}"><span class="nav-symbol">${i}</span>${l}</button>`).join('')}</div></div></div>`}
function miniBody(){if(miniPage==='home')return `<div class="mobile-hero"><span class="eyebrow">EVENING, YOURS.</span><h2>${esc(state.campaign.title).replace('，','，<br>')}。</h2><p>阿芙薰衣草精油 · 晚间仪式计划</p></div><div class="mobile-pad"><div class="row between"><h2>今晚，慢一点。</h2><span class="tag">自由体验</span></div><div class="mobile-card"><h3>找到属于你的晚间仪式</h3><p>三个场景，一份给自己的留白。</p><button class="btn" data-action="mini-nav" data-value="quiz" ${!activeCampaign()?'disabled':''}>${activeCampaign()?'选择我的晚间场景':'活动已暂停或到期'}</button></div><div class="mobile-card mini-product"><img src="${BASE}/assets/evening.png" alt="薰衣草氛围插画"><div><h3>薰衣草精油 · 10ml</h3><p>参考价 ¥99</p><button class="text-link" data-action="mini-nav" data-value="product">了解这一瓶</button></div></div><div class="mobile-card"><h3>今晚的灵感活动</h3><p>一张五行签，或六道晚间偏好题。</p><a class="text-link" href="${BASE}/activities/five-elements/">领取五行签</a> · <a class="text-link" href="${BASE}/activities/evening-personality/">测测晚间偏好</a></div><p class="mini-note" style="margin-top:12px">封面为 AI 概念视觉，非实际包装。权益及订单仅作本机演示。</p></div>`;
if(miniPage==='quiz')return `<div class="mobile-pad"><button class="back-btn" data-action="mini-nav" data-value="home">返回首页</button><span class="eyebrow">YOUR EVENING MOMENT</span><h2 style="margin:15px 0 8px">今晚，你想怎么度过？</h2><p class="small muted">没有标准答案，选一个此刻喜欢的场景。</p>${Object.entries(scenes).map(([k,v],i)=>`<button class="choice ${selectedScene===k?'selected':''}" data-action="scene" data-value="${k}"><span class="choice-icon">${['☷','◒','♫'][i]}</span><div>${v[0]}<span>${['翻几页书，把时间慢下来','结束忙碌，给自己一点空白','不设闹钟，享受小小的日常'][i]}</span></div></button>`).join('')}<button class="btn full" style="margin-top:22px" data-action="scene-result" ${!selectedScene?'disabled':''}>生成我的仪式建议</button><p class="mini-note" style="margin-top:16px">这是生活方式建议，不是健康测试。</p></div>`;
if(miniPage==='result'){const s=scenes[selectedScene]||scenes.read;return `<div class="mobile-pad"><button class="back-btn" data-action="mini-nav" data-value="quiz">重新选择</button><span class="eyebrow">A MOMENT FOR YOURSELF</span><h2 style="margin:16px 0">你的${s[0]}</h2><p class="small muted">${s[1]}</p><div class="mobile-card">${s.slice(2).map((x,i)=>`<div class="roadmap-line"><span>0${i+1}</span><p>${x}</p></div>`).join('')}</div><p class="mini-note" style="margin-top:12px">如搭配精油，请先确认包装说明中的适用方式。</p><div class="coupon"><strong>¥${state.campaign.coupon}</strong><div><b class="small">晚间体验权益 · 模拟</b><p>满 ¥99 可用 / 每人一次<br>有效至 ${esc(state.campaign.end)}</p></div></div><button class="btn full" data-action="claim" ${!activeCampaign()?'disabled':''}>${state.claimed?'权益已领取 · 去看商品':activeCampaign()?'领取体验权益':'活动不可领取'}</button><p class="mini-note" style="margin-top:10px">限本演示单品，不叠加其他优惠，无实际兑换效力。</p></div>`}
if(miniPage==='product')return `<div class="mobile-pad"><button class="back-btn" data-action="mini-nav" data-value="home">返回首页</button><div style="background:#ece5f0;border-radius:12px;padding:16px"><img style="width:175px;margin:auto;mix-blend-mode:multiply" src="${BASE}/assets/evening.png" alt="阿芙薰衣草氛围插画"></div><h2 style="margin-top:19px">薰衣草精油</h2><p class="small muted">AFU 阿芙 / 10ml / 包装以店铺为准</p><div class="price">¥99 <small>参考价</small></div><div class="mobile-card"><h3>买之前，先了解</h3><p>使用方式遵循当前商品标签，不把单方精油当作可直接上脸的按摩油。</p></div><div class="mobile-total"><span>模拟权益</span><span>${validCoupon()?'-¥'+state.claimed.amount:'未领取或不可用'}</span></div><button class="btn full" data-action="mini-nav" data-value="checkout" ${!activeCampaign()?'disabled':''}>${activeCampaign()?'模拟购买':'活动暂不可购买'}</button><p class="mini-note" style="margin-top:12px">无真实收款、发货。参考价格以店铺为准，权益仅供体验。</p></div>`;
if(miniPage==='checkout')return `<div class="mobile-pad"><button class="back-btn" data-action="mini-nav" data-value="product">返回商品</button><h2>确认模拟订单</h2><div class="mobile-card"><p>演示收货信息</p><h3>体验用户 · 无需填写地址</h3><p>不会创建真实订单或收集个人信息。</p></div><div class="mobile-card mini-product"><img src="${BASE}/assets/evening.png" alt="精油氛围插画"><div><h3>阿芙薰衣草精油</h3><p>10ml × 1 / 参考价 ¥99</p></div></div><div class="mobile-total"><span>商品小计</span><span>¥99</span></div><div class="mobile-total"><span>模拟权益</span><span>-¥${validCoupon()?state.claimed.amount:0}</span></div><div class="mobile-total"><strong>模拟应付</strong><strong>¥${payable()}</strong></div><button class="btn full" data-action="order" ${!activeCampaign()?'disabled':''}>完成模拟下单 · 不扣款</button><p class="mini-note" style="margin-top:15px">本操作仅保存本机演示记录。活动券仅供首笔模拟订单使用，不叠加其他优惠。</p></div>`;
if(miniPage==='success'){const o=state.orders.at(-1);return `<div class="mobile-pad center"><div class="success-ring">✓</div><h2>模拟订单已完成</h2><p class="small muted" style="margin:14px 0 25px">没有扣款，也不会发货。<br>现在，为今晚留一个小小的仪式吧。</p><div class="mobile-card"><p>订单号 ${esc(o?.id)}</p><h3>演示金额 ¥${o?.amount}</h3></div><div class="spacer"></div><button class="btn full" data-action="mini-nav" data-value="ritual">进入晚间打卡</button><button class="text-link" style="margin-top:20px" data-action="mini-nav" data-value="mine">查看我的订单</button></div>`}
if(miniPage==='ritual')return `<div class="mobile-pad"><span class="eyebrow">SEVEN EVENINGS</span><h2 style="margin:15px 0 9px">七天，留一点空白。</h2><p class="small muted">每天一件小事，让日常有自己的节奏。</p><div class="mobile-card"><div class="row between"><h3>我的晚间记录</h3><span class="tag">${state.checkins.length} / 7 天</span></div><div class="checkdays">${Array.from({length:7},(_,i)=>`<div class="day ${i<state.checkins.length?'done':''}">${i<state.checkins.length?'✓':i+1}</div>`).join('')}</div><button class="btn full" data-action="checkin" ${state.checkins.includes(today())||state.checkins.length>=7?'disabled':''}>${state.checkins.length>=7?'七日计划已完成':state.checkins.includes(today())?'今晚已记录':'记录今晚的留白'}</button><p>每天可记录一次，无需分享或邀请好友。</p></div><div class="mobile-card"><h3>今晚的小建议</h3><p>把手机放远一点，翻开一本书。十分钟也可以属于你。</p><button class="text-link" data-action="mini-nav" data-value="quiz">换一个晚间场景</button></div><p class="mini-note" style="margin-top:18px">记录仅保存在当前浏览器。七日打卡不要求连续，也没有实际奖励。</p></div>`;
return `<div class="mobile-pad"><span class="eyebrow">MY LITTLE MOMENTS</span><h2 style="margin:15px 0 7px">你好，体验用户。</h2><p class="small muted">你已经为自己留下 ${state.checkins.length} 个夜晚。</p><div class="mobile-card"><h3>我的权益</h3><p>${state.claimed?`模拟 ¥${state.claimed.amount} 权益 · ${validCoupon()?'待使用':state.claimed.used?'已使用':'不可用'}<br>有效至 ${esc(state.claimed.end)}`:'还没有领取权益，先选一个晚间场景。'}</p><button class="text-link" data-action="mini-nav" data-value="${state.claimed?'product':'quiz'}">${state.claimed?'查看商品':'去参与活动'}</button></div><div class="mobile-card"><h3>我的模拟订单 · ${state.orders.length}</h3>${state.orders.length?state.orders.slice().reverse().map(o=>`<div class="roadmap-line"><div><b class="small">薰衣草精油 · ¥${o.amount}</b><p class="mini-note">${esc(o.id)} · ${esc(o.date)}<br>模拟完成 / 不发货</p></div></div>`).join(''):'<p>暂无订单记录。</p>'}</div><p class="mini-note" style="margin-top:15px">这里是浏览器中的小程序原型，没有微信账户登录，也不会向其他服务发送数据。</p></div>`}
let videoCatalog, videoTools;
function videoAdmin(){
 if(!videoCatalog||!videoTools)return '<div class="card"><h3>视频资料正在加载</h3><p>若加载失败，请刷新页面再试。</p></div>';
 const overrides=videoTools.readOverrides(localStorage);
 return `<div class="card"><h3>首页科普视频与创作者</h3><p class="small muted">以下视频和头像来自作者的公开原页面，不表示品牌合作。确认作者开播后，再设置直播状态和截止时间。</p><p class="small muted">保存仅用于本浏览器的官网预览。导出的配置需替换仓库 seo/videos/videos.json 并部署，才能对所有访客生效。尚未接入平台实时开播接口。</p><div class="row" style="margin-top:16px"><a class="btn light small-btn" href="${BASE}/#learn" target="_blank" rel="noopener">查看首页视频区 ↗</a><button class="text-link" data-action="clear-video-live">退出本机预览</button></div></div><div class="video-admin-grid">${videoCatalog.videos.map(v=>{const live=videoTools.liveState(v.author,overrides);return `<article class="card video-admin-card"><img class="video-admin-cover" src="${esc(v.cover)}" referrerpolicy="no-referrer" alt="${esc(v.title)}的视频封面"><h3>${esc(v.title)}</h3><p class="small muted">原视频：${esc(v.originalTitle)}</p><div class="video-admin-author"><img src="${esc(v.author.avatar)}" referrerpolicy="no-referrer" alt="${esc(v.author.name)}的头像"><div><a href="${esc(v.author.url)}" target="_blank" rel="noopener noreferrer">${esc(v.author.name)}</a><p class="small muted">${live.active?'直播标识有效至 '+esc(new Date(live.expires).toLocaleString('zh-CN')):'普通头像 · 未设置有效直播标识'}</p></div></div><div class="row between"><a class="text-link" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">查看原视频 ↗</a><button class="btn light small-btn" data-action="edit-video-live" data-id="${esc(v.author.id)}">维护直播状态</button></div></article>`}).join('')}</div>`;
}
function editVideoLive(id){
 if(!videoCatalog||!videoTools)return;
 const author=videoCatalog.videos.find(v=>v.author.id===id)?.author;if(!author)return;
 const overrides=videoTools.readOverrides(localStorage), live=overrides[id]||author.live;
 const expiration=new Date(live.expiresAt||Date.now()+2*60*60*1000);
 const localTime=Number.isFinite(expiration.getTime())?new Date(expiration.getTime()-expiration.getTimezoneOffset()*60000).toISOString().slice(0,16):'';
 modal(`<h2>${esc(author.name)} · 直播状态</h2><p>请先在原平台确认开播。截止时间到达后，首页会自动恢复普通头像。</p><form id="video-live-form" class="form-grid"><label>头像状态<select name="enabled"><option value="false" ${!live.enabled?'selected':''}>普通头像</option><option value="true" ${live.enabled?'selected':''}>直播中</option></select></label><label>直播间链接<input name="url" type="url" value="${esc(live.url)}" placeholder="https://live.bilibili.com/直播间数字编号"></label><label>状态截止时间（本地时间）<input name="expiresAt" type="datetime-local" value="${esc(localTime)}"></label><p class="small">只接受 B 站直播间 HTTPS 链接。直播状态最长保留 24 小时，结束后请及时恢复普通头像。此操作仅用于本浏览器预览。</p><button class="btn" type="submit">保存预览</button></form>`);
 $('#video-live-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),enabled=f.get('enabled')==='true',url=String(f.get('url')).trim(),expiry=new Date(String(f.get('expiresAt'))).getTime();if(enabled&&!videoTools.liveUrl(url))return toast('请填写有效的 B 站直播间链接');if(enabled&&(!Number.isFinite(expiry)||expiry<=Date.now()||expiry>Date.now()+86400000))return toast('请选择未来 24 小时内的截止时间');const next={...overrides,[id]:{enabled,url:enabled?videoTools.liveUrl(url):'',expiresAt:enabled?new Date(expiry).toISOString():''}};try{localStorage.setItem(videoTools.PREVIEW_KEY,JSON.stringify(next));closeModal();render();toast('已保存，当前浏览器的首页预览已同步')}catch{toast('浏览器无法保存预览')}};
}
function exportVideos(){
 if(!videoCatalog||!videoTools)return toast('视频资料尚未加载');
 const overrides=videoTools.readOverrides(localStorage), now=Date.now();
 const data={...videoCatalog,videos:videoCatalog.videos.map(v=>{const live=videoTools.liveState(v.author,overrides,now);return {...v,author:{...v.author,live:live.active?{enabled:true,url:live.url,expiresAt:new Date(live.expires).toISOString()}:{enabled:false,url:'',expiresAt:''}}}})};
 download('videos.json',JSON.stringify(data,null,2)+'\n','application/json;charset=utf-8');toast('已导出配置，替换仓库同名文件并部署后全站生效');
}
if(route==='admin'){
 Promise.all([import(BASE+'/assets/video-model.mjs'),fetch(BASE+'/assets/videos.json').then(r=>{if(!r.ok)throw new Error('视频配置不可用');return r.json()})]).then(([model,data])=>{videoTools=model;videoCatalog=data;if(adminPage==='videos')render()}).catch(()=>toast('视频配置加载失败，请刷新重试'));
 window.addEventListener('storage',e=>{if(videoTools&&e.key===videoTools.PREVIEW_KEY&&adminPage==='videos')render()});
}

function metrics(){return period==='7'?[4280,428,34,3026]:[12640,1264,101,8989]}
function admin(){return `<div class="admin"><aside class="admin-sidebar"><h3>晚间留白 · 运营台</h3>${[['overview','◫','数据概览'],['campaign','◈','活动管理'],['content','☷','内容工作台'],['videos','▷','视频与作者'],['channels','⊞','渠道与数据']].map(([r,i,l])=>`<button data-action="admin-nav" data-value="${r}" class="${adminPage===r?'active':''}"><span>${i}</span>${l}</button>`).join('')}<div class="side-bottom">浏览器演示环境<br>运营体验账户<br><br><button class="text-link" style="padding:0;font-size:12px" data-action="reset">重置演示数据</button></div></aside><div class="admin-content"><div class="admin-title"><div><h1>${{overview:'数据概览',campaign:'活动管理',content:'内容工作台',videos:'视频与作者',channels:'渠道与数据'}[adminPage]}</h1><p>晚间留白 / 阿芙薰衣草精油 10ml</p></div><div class="row">${adminPage==='overview'?`<select aria-label="模拟统计周期" id="period"><option value="7" ${period==='7'?'selected':''}>模拟近 7 天</option><option value="30" ${period==='30'?'selected':''}>模拟近 30 天</option></select>`:adminPage==='videos'?'<button class="btn small-btn" data-action="export-videos">导出上线配置</button>':adminPage==='content'?'<button class="btn small-btn" data-action="new-content">新建内容</button>':'<button class="btn light small-btn" data-action="export">导出模拟数据</button>'}</div></div><div class="notice">演示环境 · 图表均为模拟样本，非淘宝或微信真实数据。活动、内容、订单与打卡仅保存于当前浏览器。</div>${adminBody()}</div></div>`}
function adminBody(){if(adminPage==='videos')return videoAdmin();const m=metrics();if(adminPage==='overview')return `<div class="metrics">${[['活动访客',money(m[0]),'按用户去重 · 模拟'],['意向用户',money(m[1]),'仪式完成或领券去重 · 模拟'],['模拟支付订单',m[2],'独立样本，非本机体验订单'],['模拟 GMV','¥'+money(m[3]),'示例实付 ¥89 × 订单数']].map(([l,n,s])=>`<div class="metric"><p>${l}</p><strong>${n}</strong><small>${s}</small></div>`).join('')}</div><div class="grid2"><div class="card chart-card"><div class="row between"><h3>活动访问趋势</h3><span class="tag outline">${period==='7'?'7 天':'30 天分段'} · 模拟</span></div><div class="chart">${(period==='7'?[320,480,590,720,610,810,750]:[980,1640,2170,2860,2640,2350]).map((v,i)=>{let max=period==='7'?900:3200;return `<div class="chart-col"><i style="height:${v/max*100}%"></i><b style="bottom:${v/max*100}%">${v}</b><span>${period==='7'?'D'+(i+1):['1–5','6–10','11–15','16–20','21–25','26–30'][i]}</span></div>`}).join('')}</div><p class="small muted">各段合计 ${money(m[0])}；示例按用户不跨段重复构造。</p></div><div class="card"><div class="row between"><h3>体验路径</h3><span class="small muted">同一模拟样本</span></div>${[['活动访客',m[0],100],['意向用户',m[1],50],['支付订单',m[2],20]].map(([l,n,w],i)=>`<div style="margin-top:23px"><div class="row between small"><span>${l}</span><strong>${money(n)}</strong></div><div class="bar-track" style="height:17px;margin-top:9px"><div class="bar-fill" style="width:${w}%;background:${['#c4b4d1','#967eaa','#614675'][i]}"></div></div></div>`).join('')}<p class="small muted" style="margin-top:20px">意向率 ${(m[1]/m[0]*100).toFixed(1)}% · 意向到支付 ${(m[2]/m[1]*100).toFixed(1)}%<br>条形用于阶段示意，不按真实比例缩放。</p></div></div><div class="section-head" style="margin-top:30px"><h3>当前活动</h3><button class="text-link" data-action="admin-nav" data-value="campaign">管理活动</button></div>${campaignCard()}<div class="card" style="margin-top:20px"><div class="row between"><div><h3>本机交互记录</h3><p class="small muted">与上方模拟经营样本分开统计</p></div><div class="small">${state.orders.length} 笔模拟订单 · ${state.checkins.length} 天打卡</div></div></div>`;
if(adminPage==='campaign')return `${campaignCard()}<div class="grid2 section"><div class="card"><h3>活动规则</h3><ul class="detail-list"><li>适用单品：薰衣草精油 10ml。</li><li>满 ¥99 减 ¥${state.campaign.coupon}，每个演示账户限领一次。</li><li>不与其他优惠叠加；有效期至 ${esc(state.campaign.end)}。</li><li>调整券額后仅对新领取生效；已领取权益保留原金额，到期或活动暂停后不可用。</li><li>所有权益均为模拟，不可实际兑换。</li></ul></div><div class="card"><h3>浏览器内同步体验</h3><div class="roadmap-line"><span>小程序</span><p>领券金额、有效期和参与按钮同步更新。</p></div><div class="roadmap-line"><span>后台</span><p>保存至本机浏览器，刷新后仍保留。</p></div><div class="spacer"></div><a class="btn soft small-btn" href="${BASE}/mini/">查看小程序演示</a></div></div>`;
if(adminPage==='content')return `<div class="content-tools"><input id="content-search" aria-label="搜索内容标题" placeholder="搜索内容标题…" value="${esc(contentQuery)}"><select id="content-filter" aria-label="筛选渠道">${['全部渠道','小红书','抖音','官网','微信'].map(c=>`<option ${contentFilter===c?'selected':''}>${c}</option>`).join('')}</select><span class="small muted">所有发布操作仅改变本机演示状态</span></div><div id="content-table">${contentTable()}</div>`;
return `<div class="card"><div class="row between"><div><h3>统一口径，分渠道观察</h3><p class="small muted">以下为 7 天归因示例；不代表真实渠道表现。</p></div><span class="tag">模拟样本</span></div></div><div class="table-wrap" tabindex="0" role="region" aria-label="数据表格，可左右滑动" style="margin-top:22px"><table><thead><tr><th>渠道</th><th>访客</th><th>意向用户</th><th>模拟订单</th><th>模拟 GMV</th><th>角色</th></tr></thead><tbody>${channelRows().map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}<tr><td>合计</td><td>4,280</td><td>428</td><td>34</td><td>¥3,026</td><td>末次非直接点击</td></tr></tbody></table></div><div class="grid2 section"><div class="card"><h3>事件字典</h3><ul class="detail-list"><li>page_view：匿名访客与来源。</li><li>ritual_complete / coupon_claim：意向，按用户去重。</li><li>product_click：商品点击，不等于成交。</li><li>order_paid / order_refunded：支付回调与退款。</li></ul></div><div class="card"><h3>归因边界</h3><p class="small muted" style="margin-top:16px">拟采用 7 日末次非直接点击。淘宝订单须经商家报表或授权接口核对，不假定微信、网站与淘宝可自动跨端关联。</p><p class="small muted" style="margin-top:14px">净 GMV = 实付 − 退款；生产环境只在成功支付回调后记录成交。</p></div></div>`}
function channelRows(){return [['小红书','1,800','180','14','¥1,246','场景认知'],['抖音','1,420','142','11','¥979','短视频触达'],['官网直接','600','60','5','¥445','产品教育'],['微信','460','46','4','¥356','复访服务']]}
function campaignCard(){return `<div class="card campaign-row"><div class="mini-cover"></div><div><div class="row wrap"><h3>${esc(state.campaign.title)}</h3><span class="tag ${activeCampaign()?'':'warn'}">${activeCampaign()?'演示进行中':state.campaign.active?'已到期':'已暂停'}</span></div><p class="small muted" style="margin-top:7px">薰衣草精油 10ml · 模拟满 ¥99 减 ¥${state.campaign.coupon} · 截至 ${esc(state.campaign.end)}</p></div><div class="row"><button class="switch ${state.campaign.active?'':'off'}" data-action="toggle-campaign">${state.campaign.active?'暂停活动':'恢复活动'}</button><button class="btn light small-btn" data-action="edit-campaign">编辑</button></div></div>`}
function contentTable(){const rows=state.contents.filter(c=>(contentFilter==='全部渠道'||c.channel===contentFilter)&&c.title.toLowerCase().includes(contentQuery.toLowerCase()));return rows.length?`<div class="table-wrap" tabindex="0" role="region" aria-label="数据表格，可左右滑动"><table><thead><tr><th>内容标题</th><th>渠道</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(c.channel)}</td><td><span class="tag ${c.status==='草稿'?'outline':''}">${esc(c.status)}</span></td><td><button class="text-link" data-action="edit-content" data-id="${c.id}">编辑</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">没有匹配的内容。试试其他标题或渠道。</div>'}
function editCampaign(){modal(`<h2>编辑晚间活动</h2><p>修改将在小程序体验中同步，仅保存在当前浏览器。</p><form id="campaign-form" class="form-grid two"><label class="full">活动标题<input name="title" value="${esc(state.campaign.title)}" required maxlength="24"></label><label>模拟优惠金额（元）<input type="number" name="coupon" min="1" max="98" step="1" value="${state.campaign.coupon}" required></label><label>活动有效期<input type="date" name="end" value="${esc(state.campaign.end)}" required></label><p class="small full">满 ¥99 可用。新券额仅影响后续领取，已领取的券保持原金额；活动暂停时所有权益不可用。</p><button class="btn full" type="submit">保存活动</button></form>`);$('#campaign-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const title=String(f.get('title')).trim();if(!title)return toast('请输入活动标题');state.campaign={...state.campaign,title,coupon:Number(f.get('coupon')),end:String(f.get('end'))};save();closeModal();render();toast('已保存，小程序体验已同步')}}
function editContent(id){const item=state.contents.find(c=>c.id===id)||{title:'',channel:'小红书',status:'草稿',body:''};modal(`<h2>${id?'编辑内容':'新建内容'}</h2><p>此处发布仅改变演示状态，不会发送到任何社交平台。</p><form id="content-form" class="form-grid two"><label class="full">内容标题<input name="title" required maxlength="60" value="${esc(item.title)}"></label><label>渠道<select name="channel">${['小红书','抖音','官网','微信'].map(c=>`<option ${c===item.channel?'selected':''}>${c}</option>`).join('')}</select></label><label>演示状态<select name="status">${['草稿','待审核','演示已发布'].map(c=>`<option ${c===item.status?'selected':''}>${c}</option>`).join('')}</select></label><label class="full">内容与脚本<textarea name="body" required maxlength="3000">${esc(item.body)}</textarea></label><button class="btn full" type="submit">保存内容</button></form>`);$('#content-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);let data={id:id||Date.now(),title:String(f.get('title')).trim(),channel:f.get('channel'),status:f.get('status'),body:String(f.get('body')).trim()};if(!data.title||!data.body)return toast('标题和正文不能为空');if(id)state.contents=state.contents.map(c=>c.id===id?data:c);else state.contents.push(data);save();closeModal();render();toast('内容已保存至本机演示')}}
function render(){const miniChanged=route==='mini'&&renderedMiniPage!==null&&renderedMiniPage!==miniPage;renderedMiniPage=miniPage;document.title=({mini:'小程序体验',admin:'管理后台演示'})[route]+' · 晚间留白';$('#app').innerHTML=({mini,admin})[route]();document.querySelectorAll('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===route);a.setAttribute('aria-current',a.dataset.route===route?'page':'false')});if($('#period'))$('#period').onchange=e=>{period=e.target.value;render()};if($('#content-filter'))$('#content-filter').onchange=e=>{contentFilter=e.target.value;$('#content-table').innerHTML=contentTable()};if($('#content-search'))$('#content-search').oninput=e=>{contentQuery=e.target.value;$('#content-table').innerHTML=contentTable()};if(miniChanged&&window.matchMedia('(max-width:760px)').matches)$('#phone-body')?.scrollIntoView({block:'start',behavior:'instant'})}
document.addEventListener('click',e=>{const scroll=e.target.closest('[data-scroll]');if(scroll){e.preventDefault();document.getElementById(scroll.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,v=b.dataset.value;if(a==='go-mini'){miniPage='home';goto('mini')}else if(a==='mini-nav'){miniPage=v;render()}else if(a==='scene'){selectedScene=v;render()}else if(a==='scene-result'){if(selectedScene){miniPage='result';render()}}else if(a==='claim'){if(!activeCampaign())return toast('活动已暂停或到期');if(!state.claimed){state.claimed={amount:state.campaign.coupon,end:state.campaign.end,used:false};save();toast('模拟权益已领取，不具有实际兑换效力')}miniPage='product';render()}else if(a==='order'){if(!activeCampaign())return toast('活动已暂停或到期');const amount=payable();state.orders.push({id:'DEMO-'+Date.now().toString(36).toUpperCase(),amount,date:today()});if(validCoupon())state.claimed.used=true;save();miniPage='success';render()}else if(a==='checkin'){if(!state.checkins.includes(today())&&state.checkins.length<7){state.checkins.push(today());save();render();toast('今晚已记录，明天再为自己留一点时间')}}else if(a==='admin-nav'){adminPage=v;render()}else if(a==='toggle-campaign'){state.campaign.active=!state.campaign.active;save();render();toast(state.campaign.active?'演示活动已恢复':'演示活动已暂停')}else if(a==='edit-video-live')editVideoLive(b.dataset.id);else if(a==='export-videos')exportVideos();else if(a==='clear-video-live'){try{localStorage.removeItem(videoTools.PREVIEW_KEY);render();toast('已退出直播状态预览')}catch{toast('无法清除预览')}}else if(a==='edit-campaign')editCampaign();else if(a==='new-content')editContent();else if(a==='edit-content')editContent(Number(b.dataset.id));else if(a==='export'){const lines=[['渠道','访客（模拟）','意向用户（模拟）','订单（模拟）','GMV（模拟）','角色'],...channelRows()];download('晚间留白-模拟渠道数据.csv','\uFEFF'+lines.map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('已导出模拟渠道数据')}else if(a==='reset'){modal('<h2>重置本机演示？</h2><p>将清除本机模拟订单、领券、打卡和内容修改，并恢复初始活动。不会影响任何真实业务。</p><div class="row" style="margin-top:25px"><button class="btn" data-action="confirm-reset">重置演示</button><button class="btn light" data-action="close">取消</button></div>')}else if(a==='confirm-reset'){state=defaults();save();closeModal();render();toast('已恢复初始演示数据')}else if(a==='close')closeModal();});
window.addEventListener('storage',e=>{if(e.key==='evening-pages-demo-v1'){try{const next=JSON.parse(e.newValue);if(next?.campaign&&Array.isArray(next.contents)){state=next;render();}}catch{}}});
render();
