"""Consumer-facing editorial pages, shared by preview and public builds."""
from html import escape as E
from activities import teaser
from videos import video_section

def consumer_pages(page, product, date):
    product_path='/products/afu-lavender-essential-oil-10ml/'
    guide='/guides/choosing-lavender-essential-oil/'
    faq='/faq/'
    about='/about/'
    name=E(product['name'])
    source=f'''<details class="source-details"><summary>产品信息来源</summary><p>产品名称与 10ml 规格参考 <a href="{E(product['source'])}" target="_blank" rel="noopener">CNPP 商品介绍</a>。资料阅读日期：{date}。购买时请以店铺当前商品信息为准。</p></details>'''
    crumb=lambda label:f'<nav class="crumb" aria-label="面包屑"><a href="/">首页</a> / {label}</nav>'
    pages={}
    home=f'''<section class="hero consumer-hero"><img src="/assets/evening.png" width="1536" height="1024" fetchpriority="high" alt="薰衣草与精油瓶的晚间静物插画"><div class="hero-content"><p class="eyebrow">EVENING, YOURS.</p><h1>把夜晚，<br>还给自己。</h1><p class="headline">一段音乐，一页书，一点自己的时间。</p><p class="intro">合上电脑，让今天在这里停一停。选一个喜欢的小仪式，给今晚留一点空白。</p><div class="actions"><a class="btn" href="/activities/">找到我的晚间灵感 →</a><a class="btn hero-secondary" href="{product_path}">认识薰衣草精油</a></div></div><span class="caption">氛围插画 · 商品包装以实物为准</span></section>'''
    home+=teaser()
    home+=video_section()
    home+=f'''<section class="band"><div class="container featured-product"><div><p class="eyebrow">A LITTLE LAVENDER</p><h2>认识这一瓶薰衣草精油。</h2><p class="lead">{name}</p><p>想把香气加入日常？先认识产品，再选择适合自己的使用方式。</p><div class="product-tags"><span>阿芙 AFU</span><span>薰衣草单方精油</span><span>10ml</span></div></div><div class="product-summary"><p class="small">参考价格</p><p class="consumer-price">¥99 <small>/ 10ml</small></p><p class="reference">实际价格与优惠以店铺结算页为准。</p><div class="actions"><a class="btn" href="{product_path}">了解这瓶精油 →</a><a class="btn light" href="{guide}">新手选购指南</a></div></div></div></section><section class="container"><p class="eyebrow">SMALL THINGS, YOUR WAY</p><h2>今晚，可以从一件小事开始。</h2><div class="grid"><article class="box"><div class="number">01</div><h3>合上电脑</h3><p>给今天画一个句号，把接下来的时间留给自己。</p></article><article class="box"><div class="number">02</div><h3>翻开一本书</h3><p>不设阅读目标，只读此刻想读的一页。</p></article><article class="box"><div class="number">03</div><h3>记下一个瞬间</h3><p>一首歌、一盏灯，或是一件值得保留的小事。</p></article></div><p class="reference">生活方式灵感供你自由选择；精油的使用方式请遵循商品标签。</p></section>'''
    pages['/']=page('/','晚间留白｜晚间灵感、趣味测试与阿芙薰衣草精油 10ml','给自己一段晚间留白：领取五行灵感签，探索你的晚间充电方式，了解阿芙薰衣草精油 10ml 与新手选购指南。',home)
    body=f'''<article class="container">{crumb('薰衣草精油')}<div class="product-intro"><div><p class="eyebrow">LAVENDER / AFU</p><h1>阿芙薰衣草精油</h1><p class="lead">从了解一瓶精油开始，找到你喜欢的日常。</p><div class="product-tags"><span>10ml</span><span>薰衣草单方精油</span><span>阿芙 AFU</span></div><div class="actions"><a class="btn" href="{guide}">看看怎么选 →</a><a class="btn light" href="{faq}#buy">了解购买方式</a></div></div><aside class="product-summary"><p class="small">10ml · 参考价格</p><p class="consumer-price">¥99</p><p class="reference">实际价格、优惠与库存以店铺为准。</p></aside></div><section class="section"><h2>先认识，再带回日常。</h2><div class="grid"><article class="box"><h3>这是一款什么产品？</h3><p>阿芙品牌的薰衣草单方精油。选购时认准完整商品名与 10ml 规格。</p></article><article class="box"><h3>怎样开始了解？</h3><p>先想想自己希望的使用场景，再阅读商品标签，确认适用方式与注意事项。</p></article><article class="box"><h3>适合怎样的晚间？</h3><p>阅读、听歌或整理桌面，可以成为你的晚间主题。搭配产品前，请先确认标签说明。</p></article></div></section><section class="section content"><h2>关于这一瓶</h2><dl class="facts"><div><dt>商品名称</dt><dd>{name}</dd></div><div><dt>品牌</dt><dd>阿芙 AFU</dd></div><div><dt>产品类型</dt><dd>薰衣草单方精油</dd></div><div><dt>规格</dt><dd>10ml</dd></div><div><dt>参考价格</dt><dd>¥99，实际以店铺结算页为准</dd></div><div><dt>使用说明</dt><dd>以商品标签和随附说明为准</dd></div></dl><p class="reference">单方精油使用前请阅读标签，确认稀释要求及适用方式。</p>{source}</section><section class="section product-cta"><h2>还没想好今晚做什么？</h2><p>先领一张五行签，或用六道题找到你的晚间充电方式。</p><div class="actions"><a class="btn" href="/activities/">发现我的晚间灵感 →</a><a class="btn light" href="{faq}">查看常见问题</a></div></section></article>'''
    pages[product_path]=page(product_path,'阿芙薰衣草精油 10ml｜产品介绍、参考价格与选购｜晚间留白',product['description'],body,product=True)
    body=f'''<article class="container content">{crumb('新手指南')}<p class="eyebrow">YOUR FIRST BOTTLE</p><h1>第一次选精油，<br>从这四件事开始。</h1><p class="lead">香气是个人的喜好。把产品类型、规格、用法和购买条件看清楚，选择就会更从容。</p><div class="contents"><strong>四步选购</strong><ul><li><a href="#type">认识产品类型</a></li><li><a href="#size">选对规格与价格</a></li><li><a href="#label">阅读使用说明</a></li><li><a href="#seller">确认店铺与售后</a></li></ul></div><section id="type" class="section"><h2>01 / 先看产品类型</h2><p>单方精油、复方精油、基础油和纯露，是不同类型的产品。别只看“薰衣草”三个字，完整商品名称、成分和标签更能帮助你选择。</p><p>这里介绍的是阿芙薰衣草单方精油，规格为 10ml。</p></section><section id="size" class="section"><h2>02 / 比较同规格的价格</h2><p>确认自己选的是单瓶还是套装，再比较实际结算金额、赠品和运费。不同容量的产品，可以换算每毫升的价格后再看。</p><div class="guide-product"><h3>阿芙薰衣草精油 · 10ml</h3><p>参考价格 <strong>¥99</strong>，实际价格及优惠以店铺结算页为准。</p><a href="{product_path}">了解产品 →</a></div></section><section id="label" class="section"><h2>03 / 用法从标签开始</h2><p>购买前先确认是否适用于你计划的使用方式。单方精油通常需要特别留意稀释及使用限制，请按照这一瓶产品的标签操作。</p><p>设备适配、接触皮肤方式和用量，都应阅读商品说明；有疑问时先问店铺客服。</p></section><section id="seller" class="section"><h2>04 / 把售后也看清楚</h2><p>选择店铺时查看经营主体、品牌授权与售后规则。下单前确认规格、发货安排、运费和退换货条件，收到后核对包装与标签。</p></section><div class="actions"><a class="btn" href="{product_path}">回到产品介绍</a><a class="btn light" href="/activities/">发现今晚的小仪式</a></div></article>'''
    pages[guide]=page(guide,'薰衣草精油怎么选？四步新手选购指南｜晚间留白','第一次选薰衣草精油，从类型、容量、使用说明与售后四步开始。了解阿芙薰衣草精油 10ml 的参考价格和购买注意事项。',body)
    answers=[('spec','这瓶精油是多少毫升？','这里介绍的是阿芙薰衣草精油 10ml 单瓶。下单时请确认所选规格，单瓶和套装可能有不同的价格与内容。'),('price','参考价 ¥99 是到手价吗？','¥99 是本站展示的参考价格，供你了解产品时参考。它不代表店铺当前成交价，实际优惠、运费和支付金额以结算页为准。'),('use','第一次使用，应该注意什么？','请先阅读商品标签和使用说明，确认适用方式、用量、稀释要求及注意事项；有疑问时向店铺客服咨询。'),('buy','在哪里购买？','可在你常用的购物平台搜索“阿芙 薰衣草精油 10ml”，核对店铺主体、品牌授权、商品规格与售后规则后再下单。晚间留白提供产品介绍，不办理销售或收款。'),('test','测试结果能帮我选产品吗？','测试提供晚间生活灵感，你可以自由选择喜欢的行动。产品是否适合自己，需要结合使用场景与商品说明判断。'),('sleep','精油可以治疗失眠吗？','精油不作为失眠治疗方式。这里的阅读、音乐与小仪式是生活灵感；涉及健康问题时，请寻求专业帮助。'),('official','晚间留白和阿芙是什么关系？','晚间留白是独立生活方式网站，介绍阿芙产品供读者了解，不是阿芙官方网站或授权店铺。')]
    body=f'''<article class="container content">{crumb('常见问题')}<p class="eyebrow">A FEW THINGS TO KNOW</p><h1>你可能还想知道。</h1><p class="lead">选购、使用和活动体验的小问题，在这里找到答案。</p><div class="faq">{''.join(f'<details id="{key}" {"open" if key in ("price","buy") else ""}><summary>{q}</summary><p>{answer}</p></details>' for key,q,answer in answers)}</div><div class="actions"><a class="btn" href="{product_path}">了解阿芙薰衣草精油</a><a class="btn light" href="/activities/">去看看晚间活动</a></div></article>'''
    pages[faq]=page(faq,'精油与晚间活动常见问题｜价格、使用和购买｜晚间留白','阿芙薰衣草精油 10ml 的参考价格、购买方式、使用说明，以及五行签和晚间偏好测试的常见问题。',body)
    body=f'''<article class="container content">{crumb('关于晚间留白')}<p class="eyebrow">OUR LITTLE SPACE</p><h1>给日常，留一点自己。</h1><p class="lead">晚间留白想陪你发现那些很小、却属于自己的时刻。一页书、一段音乐，或是一次有趣的自我探索，都是夜晚可以有的样子。</p><section class="section"><h2>在这里，你可以做什么？</h2><p>领一张五行主题灵感签，探索自己的晚间偏好，或者认识阿芙薰衣草精油 10ml。每个小行动，都由你决定要不要带进生活。</p></section><section class="section"><h2>关于产品介绍</h2><p>晚间留白是独立生活方式网站，不是阿芙官方网站或授权销售店铺。品牌名称用于介绍对应产品，购买请通过你确认的店铺完成。</p><p>¥99 为本站展示的参考价格，实际售价与优惠以店铺为准。产品信息参考具名来源，使用方式以实物标签为准。</p>{source}<p class="reference">站内主视觉为 AI 氛围插画，商品包装以实物为准。</p></section><section class="section"><h2>关于活动与隐私</h2><p>五行签是文化主题娱乐；晚间充电测试是原创趣味偏好测试，供自我探索，不作心理诊断。</p><p>参加活动无需登录或提交手机号、出生信息。答案只用于当前页面生成结果，刷新即清除。分享与下载由你主动选择。网站托管服务可能保留基础访问日志。</p><p>科普视频的封面与头像由哔哩哔哩资源加载；点击观看后才加载第三方播放器。播放与创作者主页由原平台提供，访问时适用原平台的隐私规则。</p></section><div class="actions"><a class="btn" href="/activities/">开始一段晚间留白 →</a></div></article>'''
    pages[about]=page(about,'关于晚间留白｜生活灵感、产品介绍与隐私说明','认识晚间留白：一个分享晚间生活灵感、趣味自我探索与阿芙薰衣草精油介绍的独立网站，了解内容来源和活动隐私。',body,kind='AboutPage')
    return pages
